import { mkdir, writeFile } from "node:fs/promises";

const characters = [..."あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん"];
const output = [];
for (const character of characters) {
  const code = character.codePointAt(0).toString(16).padStart(5, "0");
  const url = `https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/${code}.svg`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`No se pudo descargar ${character}: ${response.status}`);
  const svg = await response.text();
  const paths = [...svg.matchAll(/<path[^>]+d="([^"]+)"/g)].map((match) => match[1]);
  const labels = [...svg.matchAll(/<text transform="matrix\(1 0 0 1 ([\d.]+) ([\d.]+)\)">(\d+)<\/text>/g)].map((match) => ({ x: Number(match[1]), y: Number(match[2]), number: Number(match[3]) }));
  if (!paths.length) throw new Error(`Sin trazos para ${character}`);
  output.push([character, { character, viewBox: "0 0 109 109", paths, labels }]);
}
await mkdir("src/data", { recursive: true });
await writeFile("src/data/hiragana-strokes.ts", `// Derived from KanjiVG (Ulrich Apel), CC BY-SA 3.0.\n// https://kanjivg.tagaini.net/ — generated by scripts/import-kanjivg.mjs\nimport type { KanaStrokeData } from \"@/lib/drawing/types\";\n\nexport const hiraganaStrokeData: Readonly<Record<string, KanaStrokeData>> = ${JSON.stringify(Object.fromEntries(output), null, 2)};\n`);
